### ISSUE TITLE
Changes in structure / better developer experience

### ISSUE THREAD

**Issue by nonZero** [omerda123/Callaby#2]
Hi!

* [x] Please get rid of `src` and collapse all into `/`.
* [x] Pipfile: Please remove`docker`, `uuid`, `logging`. Please add ipython and django-extensions for ease of developing. 

Udi

**Comment by omerda123** [comment]
I did it.
please explain me why i needed to uninstall docker, uuid, logging from pipenv?

**Comment by nonZero** [comment]
docker is not a python package
uuid and logging are in the standard lib
